EMBEDDING_MODEL = "text-embedding-ada-002"
PG_COLLECTION_NAME = "pdf_rag"
EMBEDDING_MODEL_NAME = "BAAI/bge-large-zh"
HF_REPO_ID = "mistralai/Mistral-7B-Instruct-v0.2"
#HF_REPO_ID = "gpt2"
CHAT_LLM = "HF"
TEXT_SPLITTER = "character"
POSTGRES_CONNECTION = "postgresql+psycopg://postgres:qwer1234@localhost:5433/vector_rag"
