EMBEDDING_MODEL = "text-embedding-ada-002"
PG_COLLECTION_NAME = "pdf_rag"
EMBEDDING_MODEL_NAME = "BAAI/bge-large-zh"
#HF_REPO_ID = "mistralai/Mixtral-8x7B-v0.1"
HF_REPO_ID = "microsoft/DialoGPT-small"
CHAT_LLM = "openAI"
TEXT_SPLITTER = "character"
POSTGRES_CONNECTION = "postgresql+psycopg://postgres:qwer1234@localhost:5433/vector_rag"
